Ss 25 set up portfolio page
Gujsingh/StockCSE115A pull request #13
Opened 2022-02-09 05:52 UTC by nreusken

The portfolio part should be working. The dashboard is not totally finished, missing the news and not the correct top movers but will be working on that later this week.

2022-02-09 16:51 UTC, ojas1542 requested changes
Dashboard and portfolio are looking really good so far. Just a few minor issues:
1) There are some unnecessary console.log statements 
2) Spacing is inconsistent in some places(like with the class components)
3) Some lines of code are too long and should be wrapped

2022-02-09 16:56 UTC, ojas1542 commented on frontend/src/components/Dashboard.js
> +        portfolio.push(createData(key, portfolioDict[key]['amount'], portfolioDict[key]['shares'], data[key]['latestTrade']['p'], data[key]['dailyBar']['h'], data[key]['dailyBar']['l'], data[key]['pr
could wrap this line since it's kinda long.

2022-02-09 17:41 UTC, mihika-marathe commented
Is the profile button on the menu and on the drawer intentional?

2022-02-11 05:23 UTC, mihika-marathe approved these changes

2022-02-11 05:30 UTC, Gujsingh approved these changes
Looks good to me

2022-02-11 07:36 UTC, ojas1542 requested changes
Still seeing the inconsistent indent spacing in places like Dashboard.js

2022-02-14 23:49 UTC, ojas1542 approved these changes

2022-02-15 05:49 UTC, merged