Alpacas
Gujsingh/StockCSE115A pull request #9
Opened 2022-02-04 21:08 UTC by Gujsingh

2022-02-04 22:09 UTC, nreusken requested changes

2022-02-04 22:09 UTC, nreusken commented on frontend/src/components/StockPage/services/polygon.js
> +    const quote = (symbol) => api.get('/v2/stocks/{symbol}/quotes/latest')
I think this should be api.get('/v2/stocks/' +symbol + '/quotes/latest'). Same for the other functions

2022-02-04 23:20 UTC, ojas1542 commented on frontend/src/components/StockPage/alpacas.js
> +        retrun <View>
return?

2022-02-04 23:42 UTC, ojas1542 requested changes
I'm seeing syntax errors in alpacas.js, login.js and register.js

2022-02-06 21:47 UTC, ojas1542 requested changes
After fixing the body in register.js I still get the following console errors when trying to run the login and register page.

<img width="613" alt="Screen Shot 2022-
<img width="613" alt="Screen Shot 2022-02-06 at 1 43 44 PM" src="https://user-images.githubusercontent.com/17942486/152702624-8e8dd9d5-03f5-4ee5-a988-0abfca6fe6dc.png">
02-06 at 1 43 23 PM" src="https://user-images.githubusercontent.com/17942486/152702614-d4a88d8c-3084-4277-9d57-a45200acbcf6.png">

2022-02-06 21:47 UTC, ojas1542 commented on frontend/src/components/login/register.js
> +                      })
This won't compile. Should be in the form f_name:fName

2022-02-07 02:41 UTC, ojas1542 requested changes

2022-02-07 02:41 UTC, ojas1542 commented on frontend/src/components/login/register.js
> +                   console.log(this.state)
The server response also needs to be checked to see if account creation was successful cuz I'm not seeing any error messages when I incorrectly fill out the fields.

2022-02-07 02:41 UTC, ojas1542 commented on frontend/src/components/login/login.js
> +                            console.log(token)
the console.log statements are good for debugging but I feel like they should be commented out when pushing to the main branch

2022-02-07 02:48 UTC, ojas1542 approved these changes

2022-02-07 02:51 UTC, ojas1542 approved these changes
Looking good. All the console.log statements are good for debugging but should be ideally commented out when merging. The server response also needs to be checked when creating an account but these changes aren't super important so we can just have them be part of a future pr.

2022-02-07 04:58 UTC, nreusken approved these changes
Looks good for merge. I agree with the comments made by Ojas!

2022-02-07 05:01 UTC, merged